INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('10000', 'ASET', 'ASSET', 'DEBIT', NULL, 1, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11000', 'ASET LANCAR', 'ASSET', 'DEBIT', '59f93483-d0fe-4dd9-828a-bee36cbad57b', 2, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11100', 'KAS', 'ASSET', 'DEBIT', '84214008-04dc-42c2-bdba-3a037641db2d', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11101', 'Kas Operasional', 'ASSET', 'DEBIT', 'f1753640-4147-427d-b7ea-b39420732f8a', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11102', 'Kas Kecil', 'ASSET', 'DEBIT', 'f1753640-4147-427d-b7ea-b39420732f8a', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11103', 'Kas Proyek', 'ASSET', 'DEBIT', 'f1753640-4147-427d-b7ea-b39420732f8a', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11104', 'Kas Kantor', 'ASSET', 'DEBIT', 'f1753640-4147-427d-b7ea-b39420732f8a', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11200', 'BANK', 'ASSET', 'DEBIT', '84214008-04dc-42c2-bdba-3a037641db2d', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11201', 'Bank Bni', 'ASSET', 'DEBIT', '1bb8924f-4a71-4bc3-acba-b71f6a29172a', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11202', 'Bank Bca', 'ASSET', 'DEBIT', '1bb8924f-4a71-4bc3-acba-b71f6a29172a', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11203', 'Bank Mandiri', 'ASSET', 'DEBIT', '1bb8924f-4a71-4bc3-acba-b71f6a29172a', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11300', 'PIUTANG', 'ASSET', 'DEBIT', '84214008-04dc-42c2-bdba-3a037641db2d', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11301', 'Piutang Usaha', 'ASSET', 'DEBIT', 'a3765d46-7288-4abd-b6d5-4bf8a5302d6d', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11302', 'Piutang Termin', 'ASSET', 'DEBIT', 'a3765d46-7288-4abd-b6d5-4bf8a5302d6d', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11303', 'Piutang Retensi', 'ASSET', 'DEBIT', 'a3765d46-7288-4abd-b6d5-4bf8a5302d6d', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11304', 'Piutang Lainya', 'ASSET', 'DEBIT', 'a3765d46-7288-4abd-b6d5-4bf8a5302d6d', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11400', 'PERSEDIAAN', 'ASSET', 'DEBIT', '84214008-04dc-42c2-bdba-3a037641db2d', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11401', 'Persediaan Material', 'ASSET', 'DEBIT', '145f848b-e667-475a-a804-887f7dd1b2ab', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11402', 'Persediaan Material Umum', 'ASSET', 'DEBIT', '145f848b-e667-475a-a804-887f7dd1b2ab', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11403', 'Persediaan Material Lainya', 'ASSET', 'DEBIT', '145f848b-e667-475a-a804-887f7dd1b2ab', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11500', 'UANG MUKA', 'ASSET', 'DEBIT', '84214008-04dc-42c2-bdba-3a037641db2d', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11501', 'Uang Muka Pembelian', 'ASSET', 'DEBIT', 'cdb3b0af-e798-42c0-9735-620d6b459111', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11502', 'Uang Muka Subkontraktor', 'ASSET', 'DEBIT', 'cdb3b0af-e798-42c0-9735-620d6b459111', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11503', 'Uang Muka Karyawan', 'ASSET', 'DEBIT', 'cdb3b0af-e798-42c0-9735-620d6b459111', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11600', 'BIAYA DIBAYAR DIMUKA', 'ASSET', 'DEBIT', '84214008-04dc-42c2-bdba-3a037641db2d', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11601', 'Sewa Dibayar Dimuka', 'ASSET', 'DEBIT', 'a7fb5438-8f8e-48a0-a2fd-8e451ede540e', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11602', 'Asuransi Dibayar Dimuka', 'ASSET', 'DEBIT', 'a7fb5438-8f8e-48a0-a2fd-8e451ede540e', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11700', 'PAJAK DIBAYAR DIMUKA', 'ASSET', 'DEBIT', '84214008-04dc-42c2-bdba-3a037641db2d', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11701', 'PPN Masukan', 'ASSET', 'DEBIT', '7a3e6cc5-0e7e-4613-b9da-d724cd370e60', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11702', 'PPh 22 Dibayar Dimuka', 'ASSET', 'DEBIT', '7a3e6cc5-0e7e-4613-b9da-d724cd370e60', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11703', 'PPh 23 Dibayar Dimuka', 'ASSET', 'DEBIT', '7a3e6cc5-0e7e-4613-b9da-d724cd370e60', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('11704', 'PPh 25 Dibayar Dimuka', 'ASSET', 'DEBIT', '7a3e6cc5-0e7e-4613-b9da-d724cd370e60', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12000', 'ASET TIDAK LANCAR', 'ASSET', 'DEBIT', '59f93483-d0fe-4dd9-828a-bee36cbad57b', 2, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12100', 'ASET TETAP', 'ASSET', 'DEBIT', 'd5049658-dfa9-4c9b-b4eb-8342af12c03c', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12101', 'Tanah', 'ASSET', 'DEBIT', '54c462c2-bcab-48f9-a7a6-cc950dfcce14', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12102', 'Bangunan', 'ASSET', 'DEBIT', '54c462c2-bcab-48f9-a7a6-cc950dfcce14', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12103', 'Kendaraan', 'ASSET', 'DEBIT', '54c462c2-bcab-48f9-a7a6-cc950dfcce14', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12104', 'Mesin dan Peralatan', 'ASSET', 'DEBIT', '54c462c2-bcab-48f9-a7a6-cc950dfcce14', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12105', 'Peralatan Proyek', 'ASSET', 'DEBIT', '54c462c2-bcab-48f9-a7a6-cc950dfcce14', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12106', 'Peralatan Kantor', 'ASSET', 'DEBIT', '54c462c2-bcab-48f9-a7a6-cc950dfcce14', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12200', 'AKUMULASI PENYUSUTAN', 'CONTRA_ASSET', 'CREDIT', 'd5049658-dfa9-4c9b-b4eb-8342af12c03c', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12201', 'Akumulasi Penyusutan Bangunan', 'CONTRA_ASSET', 'CREDIT', '7f8c0cc2-1fdf-4034-b437-1bfb3a69ddc5', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12202', 'Akumulasi Penyusutan Kendaraan', 'CONTRA_ASSET', 'CREDIT', '7f8c0cc2-1fdf-4034-b437-1bfb3a69ddc5', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12203', 'Akumulasi Penyusutan Mesin dan Peralatan', 'CONTRA_ASSET', 'CREDIT', '7f8c0cc2-1fdf-4034-b437-1bfb3a69ddc5', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12204', 'Akumulasi Penyusutan Peralatan Proyek', 'CONTRA_ASSET', 'CREDIT', '7f8c0cc2-1fdf-4034-b437-1bfb3a69ddc5', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12205', 'Akumulasi Penyusutan Peralatan Kantor', 'CONTRA_ASSET', 'CREDIT', '7f8c0cc2-1fdf-4034-b437-1bfb3a69ddc5', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12300', 'ASET TAKBERWUJUD', 'ASSET', 'DEBIT', 'd5049658-dfa9-4c9b-b4eb-8342af12c03c', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12301', 'Perangkat Lunak', 'ASSET', 'DEBIT', '8ba41b67-0c9a-40f2-97eb-46a373304240', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('12302', 'Lisensi', 'ASSET', 'DEBIT', '8ba41b67-0c9a-40f2-97eb-46a373304240', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('20000', 'LIABILITAS', 'LIABILITY', 'CREDIT', NULL, 1, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21000', 'LIABILITAS JANGKA PENDEK', 'LIABILITY', 'CREDIT', '64e16b6f-1daf-4084-bf11-77a41c3e5650', 2, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21100', 'UTANG USAHA', 'LIABILITY', 'CREDIT', '2c2b7e29-99e7-4323-b255-902a277ca915', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21101', 'Utang Supplier', 'LIABILITY', 'CREDIT', '7caf3d4a-45cc-4be9-ab1c-cb65a70c5463', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21102', 'Utang Subkontraktor', 'LIABILITY', 'CREDIT', '7caf3d4a-45cc-4be9-ab1c-cb65a70c5463', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21200', 'UTANG PAJAK', 'LIABILITY', 'CREDIT', '2c2b7e29-99e7-4323-b255-902a277ca915', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21201', 'Utang PPN', 'LIABILITY', 'CREDIT', '989d9262-fa61-4f5a-977a-afdc55913436', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21202', 'Utang PPH 21', 'LIABILITY', 'CREDIT', '989d9262-fa61-4f5a-977a-afdc55913436', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21203', 'Utang PPH 22', 'LIABILITY', 'CREDIT', '989d9262-fa61-4f5a-977a-afdc55913436', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21204', 'Utang PPH 23', 'LIABILITY', 'CREDIT', '989d9262-fa61-4f5a-977a-afdc55913436', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21205', 'Utang PPh 4 Ayat 2', 'LIABILITY', 'CREDIT', '989d9262-fa61-4f5a-977a-afdc55913436', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21300', 'UANG MUKA PELANGGAN', 'LIABILITY', 'CREDIT', '2c2b7e29-99e7-4323-b255-902a277ca915', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21301', 'Uang Muka Proyek', 'LIABILITY', 'CREDIT', 'ffa0ab96-e0dc-43a7-b872-71ec5456b1a2', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21400', 'BIAYA MASIH HARUS DIBAYAR', 'LIABILITY', 'CREDIT', '2c2b7e29-99e7-4323-b255-902a277ca915', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21401', 'Biaya Masih Harus Dibayar', 'LIABILITY', 'CREDIT', '43cbfbeb-3efa-4bc0-b942-d1c182a2afd2', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21500', 'UTANG GAJI', 'LIABILITY', 'CREDIT', '2c2b7e29-99e7-4323-b255-902a277ca915', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21501', 'Utang Gaji', 'LIABILITY', 'CREDIT', 'c96eb7ee-257b-4d12-aa1d-b58bdbfa3b96', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21600', 'UTANG BPJS', 'LIABILITY', 'CREDIT', '2c2b7e29-99e7-4323-b255-902a277ca915', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('21601', 'Utang Bpjs', 'LIABILITY', 'CREDIT', '36be9789-83d1-4803-bbdb-183312c7ad68', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('22000', 'LIABILITAS JANGKA PANJANG', 'LIABILITY', 'CREDIT', '64e16b6f-1daf-4084-bf11-77a41c3e5650', 2, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('22100', 'UTANG BANK', 'LIABILITY', 'CREDIT', '46bb6697-d480-4737-8921-47512a4a9bc8', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('22101', 'Utang Bank Bni', 'LIABILITY', 'CREDIT', 'cbdbdab6-a58c-4b51-8d65-8124b121eefd', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('22102', 'Utang Bank Bca', 'LIABILITY', 'CREDIT', 'cbdbdab6-a58c-4b51-8d65-8124b121eefd', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('22103', 'Utang Bank Mandiri', 'LIABILITY', 'CREDIT', 'cbdbdab6-a58c-4b51-8d65-8124b121eefd', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('22200', 'UTANG LEASING', 'LIABILITY', 'CREDIT', '46bb6697-d480-4737-8921-47512a4a9bc8', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('22201', 'Utang Leasing Kendaraan', 'LIABILITY', 'CREDIT', 'c0aa511c-2272-42b7-b655-107ca82d5957', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('22202', 'Utang Leasing Peralatan', 'LIABILITY', 'CREDIT', 'c0aa511c-2272-42b7-b655-107ca82d5957', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('30000', 'EKUITAS', 'EQUITY', 'CREDIT', NULL, 1, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('31000', 'Modal', 'EQUITY', 'CREDIT', 'bef4673a-30c6-47a2-b860-e4a2ae8fc9d4', 2, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('31100', 'Modal Pemilik', 'EQUITY', 'CREDIT', 'adefba4c-5e92-4093-85bf-d5c171ce449f', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('31101', 'Modal Pemilik', 'EQUITY', 'CREDIT', '50d3428c-f528-4c2d-baf0-bc9615cec8a8', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('32000', 'Laba Ditahan', 'EQUITY', 'CREDIT', 'bef4673a-30c6-47a2-b860-e4a2ae8fc9d4', 2, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('32100', 'Laba Ditahan', 'EQUITY', 'CREDIT', '547b74e9-8db4-4912-9a14-2ed836dfb3ff', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('32101', 'Laba Ditahan', 'EQUITY', 'CREDIT', 'aa181019-b4de-47d4-bc1d-e89280d373db', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('33000', 'Prive', 'EQUITY', 'DEBIT', 'bef4673a-30c6-47a2-b860-e4a2ae8fc9d4', 2, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('33100', 'Prive Pemilik', 'EQUITY', 'DEBIT', '12ef8858-dfba-44f5-8ad6-d2e7bfef18f4', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('33101', 'Prive Pemilik', 'EQUITY', 'DEBIT', 'e44dc0ad-85e2-4371-b7ac-cc0e1f08e8d3', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('40000', 'PENDAPATAN', 'REVENUE', 'CREDIT', NULL, 1, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('41000', 'PENDAPATAN USAHA', 'REVENUE', 'CREDIT', 'e26cc313-9b25-415e-b3ec-975416b15256', 2, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('41100', 'PENDAPATAN PROYEK', 'REVENUE', 'CREDIT', '29526821-745d-46d8-b0e3-dd7ebeabb7eb', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('41101', 'Pendapatan Konstruksi', 'REVENUE', 'CREDIT', '177f3948-f76e-4e4b-9b3a-28ae5dd7e506', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('41102', 'Pendapatan Instalasi', 'REVENUE', 'CREDIT', '177f3948-f76e-4e4b-9b3a-28ae5dd7e506', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('41103', 'Pendapatan Pemeliharaan', 'REVENUE', 'CREDIT', '177f3948-f76e-4e4b-9b3a-28ae5dd7e506', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('41200', 'PENDAPATAN JASA', 'REVENUE', 'CREDIT', '29526821-745d-46d8-b0e3-dd7ebeabb7eb', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('41201', 'Pendapatan Jasa', 'REVENUE', 'CREDIT', 'd9af52e6-deab-4df2-8037-f05c92b869e0', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('42000', 'PENDAPATAN LAIN-LAIN', 'REVENUE', 'CREDIT', 'e26cc313-9b25-415e-b3ec-975416b15256', 2, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('42100', 'PENDAPATAN BUNGA', 'REVENUE', 'CREDIT', 'd7566c40-2628-4c25-bb21-a935d039e522', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('42101', 'Pendapatan Bunga', 'REVENUE', 'CREDIT', '6f0f1dea-435a-40a3-bbab-78f7cb17c359', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('42200', 'PENDAPATAN LAINNYA', 'REVENUE', 'CREDIT', 'd7566c40-2628-4c25-bb21-a935d039e522', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('42201', 'Pendapatan Lainnya', 'REVENUE', 'CREDIT', '03dfaeb5-24a4-4aa6-8c36-29f9dafb3afd', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('50000', 'BEBAN', 'EXPENSE', 'DEBIT', NULL, 1, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('51000', 'BEBAN PROYEK', 'EXPENSE', 'DEBIT', 'd3fef8f1-be48-4036-8f41-432cde04c830', 2, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('51100', 'BEBAN MATERIAL', 'EXPENSE', 'DEBIT', 'ee22300d-0cba-49f5-9b83-836ec0a3bfab', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('51101', 'Beban Material Proyek', 'EXPENSE', 'DEBIT', '2193c1cc-717b-4f91-bff3-d6d614d7c93c', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('51200', 'BEBAN TENAGA KERJA', 'EXPENSE', 'DEBIT', 'ee22300d-0cba-49f5-9b83-836ec0a3bfab', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('51201', 'Beban Tenaga Kerja', 'EXPENSE', 'DEBIT', 'a0f8bc79-fd72-4466-93dd-722f034be0b4', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('51300', 'BEBAN SUBKONTRAKTOR', 'EXPENSE', 'DEBIT', 'ee22300d-0cba-49f5-9b83-836ec0a3bfab', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('51301', 'Beban Sub Kontraktor', 'EXPENSE', 'DEBIT', 'cbc872d6-076a-4830-abf4-6a1cd3d5e1a2', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('51400', 'BEBAN SEWA ALAT', 'EXPENSE', 'DEBIT', 'ee22300d-0cba-49f5-9b83-836ec0a3bfab', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('51401', 'Beban Sewa Alat', 'EXPENSE', 'DEBIT', '8c558f60-6822-4fa5-ac34-a34dc12e3b6f', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('51500', 'BEBAN TRANSPORTASI PROYEK', 'EXPENSE', 'DEBIT', 'ee22300d-0cba-49f5-9b83-836ec0a3bfab', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('51501', 'Beban Transportasi Proyek', 'EXPENSE', 'DEBIT', 'a9fcc383-96b2-4999-b592-9f7a8777dec4', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('51600', 'BEBAN PROYEK LAINNYA', 'EXPENSE', 'DEBIT', 'ee22300d-0cba-49f5-9b83-836ec0a3bfab', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('51601', 'Beban Proyek Lainnya', 'EXPENSE', 'DEBIT', '6cb7e9c2-fc95-4d76-9e37-15292256a308', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52000', 'BEBAN OPERASIONAL', 'EXPENSE', 'DEBIT', 'd3fef8f1-be48-4036-8f41-432cde04c830', 2, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52100', 'BEBAN GAJI', 'EXPENSE', 'DEBIT', '394d90a6-94f4-40f9-b041-e0cd37420643', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52101', 'Beban Gaji', 'EXPENSE', 'DEBIT', '15ffbe02-705e-44c2-804e-2e2ff39e5559', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52200', 'BEBAN LISTRIK DAN AIR', 'EXPENSE', 'DEBIT', '394d90a6-94f4-40f9-b041-e0cd37420643', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52201', 'Beban Listrik dan Air', 'EXPENSE', 'DEBIT', 'd6495390-331f-4fdf-a70c-f4c2a86f052b', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52300', 'BEBAN TELEKOMUNIKASI', 'EXPENSE', 'DEBIT', '394d90a6-94f4-40f9-b041-e0cd37420643', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52301', 'Beban Telekomunikasi', 'EXPENSE', 'DEBIT', '74c2a70f-4c68-4425-8687-fcc7910d69e4', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52400', 'BEBAN KANTOR', 'EXPENSE', 'DEBIT', '394d90a6-94f4-40f9-b041-e0cd37420643', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52401', 'Beban Kantor', 'EXPENSE', 'DEBIT', '07aaa9ac-acb9-4a40-9998-925b1910d6c3', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52500', 'BEBAN PENYUSUTAN', 'EXPENSE', 'DEBIT', '394d90a6-94f4-40f9-b041-e0cd37420643', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52501', 'Beban Penyusutan', 'EXPENSE', 'DEBIT', 'd0bd68b8-71a8-4b00-b561-0bb8a0e62942', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52600', 'BEBAN PERJALANAN DINAS', 'EXPENSE', 'DEBIT', '394d90a6-94f4-40f9-b041-e0cd37420643', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52601', 'Beban Perjalanan Dinas', 'EXPENSE', 'DEBIT', 'b3dbc9a5-3d65-4637-aff7-5dfe73a6f25c', 4, false, true);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52700', 'BEBAN OPERASIONAL LAINNYA', 'EXPENSE', 'DEBIT', '394d90a6-94f4-40f9-b041-e0cd37420643', 3, true, false);
INSERT INTO chart_of_accounts_templates (account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES ('52701', 'Beban Operasional Lainnya', 'EXPENSE', 'DEBIT', '5d692888-030d-4fc1-9efd-11c7bc48cb1b', 4, false, true);




SELECT
    'INSERT INTO chart_of_accounts_templates ' ||
    '(account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES (' ||
    quote_literal(account_code) || ', ' ||
    quote_literal(account_name) || ', ' ||
    quote_literal(account_type) || ', ' ||
    quote_literal(normal_balance) || ', ' ||
    COALESCE(quote_literal(parent_template_id::text), 'NULL') || ', ' ||
    account_level || ', ' ||
    is_header || ', ' ||
    is_postable ||
    ');'
FROM chart_of_accounts_templates
ORDER BY account_code asc


SELECT string_agg(
    'INSERT INTO chart_of_accounts_templates ' ||
    '(account_code, account_name, account_type, normal_balance, parent_template_id, account_level, is_header, is_postable) VALUES (' ||
    quote_literal(account_code) || ', ' ||
    quote_literal(account_name) || ', ' ||
    quote_literal(account_type) || ', ' ||
    quote_literal(normal_balance) || ', ' ||
    COALESCE(quote_literal(parent_template_id::text), 'NULL') || ', ' ||
    account_level || ', ' ||
    is_header || ', ' ||
    is_postable ||
    ');',
    E'\n'
    ORDER BY account_code
)
FROM chart_of_accounts_templates;