-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.accounting_periods
(
    period_id uuid NOT NULL DEFAULT gen_random_uuid(),
    period_name character varying(50) COLLATE pg_catalog."default",
    start_date date,
    end_date date,
    is_closed boolean DEFAULT false,
    closed_at timestamp without time zone,
    company_id uuid,
    CONSTRAINT accounting_periods_pkey PRIMARY KEY (period_id)
);

CREATE TABLE IF NOT EXISTS public.bank_accounts
(
    bank_account_id uuid NOT NULL DEFAULT gen_random_uuid(),
    account_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    account_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    account_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    bank_name character varying(100) COLLATE pg_catalog."default",
    bank_branch character varying(100) COLLATE pg_catalog."default",
    account_number character varying(50) COLLATE pg_catalog."default",
    account_holder character varying(150) COLLATE pg_catalog."default",
    currency character varying(10) COLLATE pg_catalog."default" DEFAULT 'IDR'::character varying,
    opening_balance numeric(18, 2) DEFAULT 0,
    is_default boolean DEFAULT false,
    is_active boolean DEFAULT true,
    company_id uuid NOT NULL,
    coa_id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by uuid,
    updated_at timestamp without time zone,
    updated_by uuid,
    deleted_at timestamp without time zone,
    CONSTRAINT bank_accounts_pkey PRIMARY KEY (bank_account_id),
    CONSTRAINT uq_bank_account_code UNIQUE (company_id, account_code)
);

CREATE TABLE IF NOT EXISTS public.cash_in
(
    cash_in_id uuid NOT NULL DEFAULT gen_random_uuid(),
    cash_in_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    transaction_date date NOT NULL,
    source_type character varying(30) COLLATE pg_catalog."default",
    source_id uuid,
    bank_account_id uuid NOT NULL,
    amount numeric(18, 2) NOT NULL,
    description text COLLATE pg_catalog."default",
    reference_no character varying(50) COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cash_in_pkey PRIMARY KEY (cash_in_id),
    CONSTRAINT cash_in_cash_in_code_key UNIQUE (cash_in_code)
);

CREATE TABLE IF NOT EXISTS public.cash_out
(
    cash_out_id uuid NOT NULL DEFAULT gen_random_uuid(),
    cash_out_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    transaction_date date NOT NULL,
    expense_type character varying(30) COLLATE pg_catalog."default",
    destination_id uuid,
    bank_account_id uuid NOT NULL,
    amount numeric(18, 2) NOT NULL,
    description text COLLATE pg_catalog."default",
    reference_no character varying(50) COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cash_out_pkey PRIMARY KEY (cash_out_id),
    CONSTRAINT cash_out_cash_out_code_key UNIQUE (cash_out_code)
);

CREATE TABLE IF NOT EXISTS public.cash_transfers
(
    transfer_id uuid NOT NULL DEFAULT gen_random_uuid(),
    transfer_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    from_account_id uuid NOT NULL,
    to_account_id uuid NOT NULL,
    transfer_date date NOT NULL,
    amount numeric(18, 2) NOT NULL,
    admin_fee numeric(18, 2) DEFAULT 0,
    description text COLLATE pg_catalog."default",
    reference_no character varying(50) COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cash_transfers_pkey PRIMARY KEY (transfer_id),
    CONSTRAINT cash_transfers_transfer_code_key UNIQUE (transfer_code)
);

CREATE TABLE IF NOT EXISTS public.chart_of_accounts
(
    coa_id uuid NOT NULL DEFAULT gen_random_uuid(),
    coa_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    account_type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    account_group character varying(50) COLLATE pg_catalog."default",
    parent_id uuid,
    is_header boolean DEFAULT false,
    is_postable boolean DEFAULT true,
    normal_balance character varying(10) COLLATE pg_catalog."default",
    is_cash_account boolean DEFAULT false,
    is_active boolean DEFAULT true,
    company_id uuid NOT NULL,
    level integer,
    path text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by uuid,
    updated_at timestamp without time zone,
    updated_by uuid,
    deleted_at timestamp without time zone,
    CONSTRAINT chart_of_accounts_pkey PRIMARY KEY (coa_id),
    CONSTRAINT chart_of_accounts_company_id_coa_code_key UNIQUE (company_id, coa_code)
);

CREATE TABLE IF NOT EXISTS public.chart_of_accounts_template
(
    coa_template_id uuid NOT NULL DEFAULT gen_random_uuid(),
    coa_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    account_type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    account_group character varying(50) COLLATE pg_catalog."default",
    parent_code character varying(30) COLLATE pg_catalog."default",
    is_header boolean DEFAULT false,
    normal_balance character varying(10) COLLATE pg_catalog."default",
    is_cash_account boolean DEFAULT false,
    is_active boolean DEFAULT true,
    CONSTRAINT chart_of_accounts_template_pkey PRIMARY KEY (coa_template_id)
);

CREATE TABLE IF NOT EXISTS public.clients
(
    client_id uuid NOT NULL DEFAULT gen_random_uuid(),
    client_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    client_type character varying(50) COLLATE pg_catalog."default",
    npwp character varying(30) COLLATE pg_catalog."default",
    nik character varying(30) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default",
    province character varying(100) COLLATE pg_catalog."default",
    postal_code character varying(10) COLLATE pg_catalog."default",
    country character varying(100) COLLATE pg_catalog."default" DEFAULT 'Indonesia'::character varying,
    email character varying(100) COLLATE pg_catalog."default",
    contact_person character varying(100) COLLATE pg_catalog."default",
    contact_phone character varying(30) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by uuid,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    bank_name character varying(25) COLLATE pg_catalog."default",
    account_number character varying(25) COLLATE pg_catalog."default",
    account_name character varying(25) COLLATE pg_catalog."default",
    CONSTRAINT clients_pkey PRIMARY KEY (client_id),
    CONSTRAINT clients_client_code_key UNIQUE (client_code)
)


CREATE TABLE IF NOT EXISTS public.closing_entries
(
    closing_id uuid NOT NULL DEFAULT gen_random_uuid(),
    period_id uuid NOT NULL,
    closing_date date,
    retained_earning_coa_id uuid,
    status character varying(20) COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT closing_entries_pkey PRIMARY KEY (closing_id)
);

CREATE TABLE IF NOT EXISTS public.coa_mapping
(
    mapping_id uuid NOT NULL DEFAULT gen_random_uuid(),
    transaction_type character varying(50) COLLATE pg_catalog."default",
    payment_type character varying(20) COLLATE pg_catalog."default",
    debit_coa_id uuid NOT NULL,
    credit_coa_id uuid NOT NULL,
    description text COLLATE pg_catalog."default",
    company_id uuid,
    CONSTRAINT coa_mapping_pkey PRIMARY KEY (mapping_id)
);

-- 1. Tambahkan relasi untuk Akun Debit
ALTER TABLE public.coa_mapping
ADD CONSTRAINT fk_coa_mapping_debit 
FOREIGN KEY (debit_coa_id) 
REFERENCES public.chart_of_accounts (coa_id) 
ON DELETE RESTRICT;

-- 2. Tambahkan relasi untuk Akun Kredit
ALTER TABLE public.coa_mapping
ADD CONSTRAINT fk_coa_mapping_credit 
FOREIGN KEY (credit_coa_id) 
REFERENCES public.chart_of_accounts (coa_id) 
ON DELETE RESTRICT;

-- 3. Tambahkan relasi untuk Company/Perusahaan (Sesuaikan nama tabel target jika bukan 'companies')
ALTER TABLE public.coa_mapping
ADD CONSTRAINT fk_coa_mapping_company 
FOREIGN KEY (company_id) 
REFERENCES public.company (company_id) 
ON DELETE CASCADE;

-- 4. Tambahkan pengaman agar tidak ada input kombinasi aturan yang kembar/duplikat
ALTER TABLE public.coa_mapping 
ADD CONSTRAINT unique_transaction_payment_company 
UNIQUE (transaction_type, payment_type, company_id);

delete from coa_mapping


CREATE TABLE IF NOT EXISTS public.coa_mapping_lines
(
    mapping_line_id uuid NOT NULL DEFAULT gen_random_uuid(),
    mapping_id uuid NOT NULL,
    coa_id uuid NOT NULL,
    "position" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    line_order integer DEFAULT 0,
    amount_type character varying(20) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT coa_mapping_lines_pkey PRIMARY KEY (mapping_line_id)
);

CREATE TABLE IF NOT EXISTS public.company
(
    company_id uuid NOT NULL DEFAULT gen_random_uuid(),
    legal_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    company_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    npwp character varying(30) COLLATE pg_catalog."default",
    nib character varying(30) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default",
    province character varying(100) COLLATE pg_catalog."default",
    postal_code character varying(10) COLLATE pg_catalog."default",
    country character varying(100) COLLATE pg_catalog."default" DEFAULT 'Indonesia'::character varying,
    phone character varying(30) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    website character varying(100) COLLATE pg_catalog."default",
    company_type character varying(50) COLLATE pg_catalog."default",
    established_date date,
    pkp boolean DEFAULT false,
    tax_number character varying(50) COLLATE pg_catalog."default",
    base_currency character varying(10) COLLATE pg_catalog."default" DEFAULT 'IDR'::character varying,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by uuid,
    updated_at timestamp without time zone,
    updated_by uuid,
    deleted_at timestamp without time zone,
    CONSTRAINT company_pkey PRIMARY KEY (company_id),
    CONSTRAINT company_company_code_key UNIQUE (company_code)
);

CREATE TABLE IF NOT EXISTS public.efaktur_exports
(
    export_id uuid NOT NULL DEFAULT gen_random_uuid(),
    export_code character varying(30) COLLATE pg_catalog."default",
    period_month integer,
    period_year integer,
    file_path text COLLATE pg_catalog."default",
    total_vat numeric(18, 2),
    status character varying(20) COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT efaktur_exports_pkey PRIMARY KEY (export_id),
    CONSTRAINT efaktur_exports_export_code_key UNIQUE (export_code)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    employee_id uuid NOT NULL DEFAULT gen_random_uuid(),
    employee_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    nik character varying(20) COLLATE pg_catalog."default",
    gender character varying(10) COLLATE pg_catalog."default",
    birth_date date,
    phone character varying(30) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    department character varying(100) COLLATE pg_catalog."default",
    "position" character varying(100) COLLATE pg_catalog."default",
    employment_type character varying(50) COLLATE pg_catalog."default",
    join_date date,
    salary_type character varying(20) COLLATE pg_catalog."default",
    basic_salary numeric(18, 2) DEFAULT 0,
    daily_wage numeric(18, 2) DEFAULT 0,
    bank_name character varying(100) COLLATE pg_catalog."default",
    bank_account_number character varying(50) COLLATE pg_catalog."default",
    bank_account_name character varying(150) COLLATE pg_catalog."default",
    cost_center character varying(50) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by uuid,
    updated_at timestamp without time zone,
    updated_by uuid,
    deleted_at timestamp without time zone,
    CONSTRAINT employees_pkey PRIMARY KEY (employee_id),
    CONSTRAINT employees_employee_code_key UNIQUE (employee_code)
);

CREATE TABLE IF NOT EXISTS public.general_ledger
(
    ledger_id uuid NOT NULL DEFAULT gen_random_uuid(),
    journal_id uuid NOT NULL,
    journal_line_id uuid NOT NULL,
    coa_id uuid NOT NULL,
    transaction_date date,
    debit numeric(18, 2) DEFAULT 0,
    credit numeric(18, 2) DEFAULT 0,
    balance numeric(18, 2) DEFAULT 0,
    project_id uuid,
    company_id uuid,
    CONSTRAINT general_ledger_pkey PRIMARY KEY (ledger_id)
);

CREATE TABLE IF NOT EXISTS public.grn
(
    grn_id uuid NOT NULL DEFAULT gen_random_uuid(),
    grn_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    purchase_id uuid NOT NULL,
    supplier_id uuid NOT NULL,
    project_id uuid NOT NULL,
    grn_date date NOT NULL,
    status character varying(30) COLLATE pg_catalog."default",
    total_amount numeric(18, 2) DEFAULT 0,
    warehouse_id uuid NOT NULL,
    company_id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT grn_pkey PRIMARY KEY (grn_id),
    CONSTRAINT grn_grn_code_key UNIQUE (grn_code)
);

CREATE TABLE IF NOT EXISTS public.grn_items
(
    grn_item_id uuid NOT NULL DEFAULT gen_random_uuid(),
    grn_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity_received numeric(18, 2) NOT NULL,
    unit_price numeric(18, 2) NOT NULL,
    batch_number character varying(50) COLLATE pg_catalog."default",
    expired_date date,
    total numeric(18, 2) DEFAULT 0,
    CONSTRAINT grn_items_pkey PRIMARY KEY (grn_item_id)
);

CREATE TABLE IF NOT EXISTS public.journal_entries
(
    journal_id uuid NOT NULL DEFAULT gen_random_uuid(),
    journal_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    journal_date date NOT NULL,
    reference_type character varying(30) COLLATE pg_catalog."default",
    reference_id uuid,
    description text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    is_posted boolean DEFAULT false,
    posted_at timestamp without time zone,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT journal_entries_pkey PRIMARY KEY (journal_id),
    CONSTRAINT journal_entries_journal_code_key UNIQUE (journal_code)
);

CREATE TABLE IF NOT EXISTS public.journal_lines
(
    journal_line_id uuid NOT NULL DEFAULT gen_random_uuid(),
    journal_id uuid NOT NULL,
    coa_id uuid NOT NULL,
    debit numeric(18, 2) DEFAULT 0,
    credit numeric(18, 2) DEFAULT 0,
    description text COLLATE pg_catalog."default",
    project_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT journal_lines_pkey PRIMARY KEY (journal_line_id)
);

CREATE TABLE IF NOT EXISTS public.journal_reversals
(
    reversal_id uuid NOT NULL DEFAULT gen_random_uuid(),
    original_journal_id uuid NOT NULL,
    reversal_journal_id uuid NOT NULL,
    reason text COLLATE pg_catalog."default",
    reversal_date date,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT journal_reversals_pkey PRIMARY KEY (reversal_id)
);

CREATE TABLE IF NOT EXISTS public.permissions
(
    permission_id uuid NOT NULL DEFAULT gen_random_uuid(),
    permission_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT permissions_pkey PRIMARY KEY (permission_id),
    CONSTRAINT permissions_permission_code_key UNIQUE (permission_code)
);

CREATE TABLE IF NOT EXISTS public.pph_withholding
(
    pph_id uuid NOT NULL DEFAULT gen_random_uuid(),
    pph_type character varying(10) COLLATE pg_catalog."default",
    reference_type character varying(30) COLLATE pg_catalog."default",
    reference_id uuid,
    base_amount numeric(18, 2) DEFAULT 0,
    tax_rate numeric(5, 2) DEFAULT 0,
    tax_amount numeric(18, 2) DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pph_withholding_pkey PRIMARY KEY (pph_id)
);

CREATE TABLE IF NOT EXISTS public.product_batches
(
    batch_id uuid NOT NULL DEFAULT gen_random_uuid(),
    product_id uuid NOT NULL,
    warehouse_id uuid NOT NULL,
    batch_number character varying(50) COLLATE pg_catalog."default",
    qty numeric(18, 2) DEFAULT 0,
    received_date date,
    expired_date date,
    cost_price numeric(18, 2) DEFAULT 0,
    company_id uuid,
    CONSTRAINT product_batches_pkey PRIMARY KEY (batch_id)
);

CREATE TABLE IF NOT EXISTS public.product_brands
(
    brand_id uuid NOT NULL DEFAULT gen_random_uuid(),
    brand_code character varying(30) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    company_id uuid,
    CONSTRAINT product_brands_pkey PRIMARY KEY (brand_id),
    CONSTRAINT product_brands_brand_code_key UNIQUE (brand_code)
);

CREATE TABLE IF NOT EXISTS public.product_categories
(
    category_id uuid NOT NULL DEFAULT gen_random_uuid(),
    category_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    company_id uuid NOT NULL,
    CONSTRAINT product_categories_pkey PRIMARY KEY (category_id),
    CONSTRAINT product_categories_company_id_category_code_key UNIQUE (company_id, category_code)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id uuid NOT NULL DEFAULT gen_random_uuid(),
    product_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    product_type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    category_id uuid,
    brand_id uuid,
    unit_id uuid,
    is_stock_item boolean DEFAULT true,
    is_active boolean DEFAULT true,
    min_stock numeric(18, 2) DEFAULT 0,
    max_stock numeric(18, 2) DEFAULT 0,
    barcode character varying(50) COLLATE pg_catalog."default",
    expense_coa_id uuid,
    inventory_coa_id uuid,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT products_pkey PRIMARY KEY (product_id),
    CONSTRAINT products_product_code_key UNIQUE (product_code)
);

CREATE TABLE IF NOT EXISTS public.project_addendums
(
    addendum_id uuid NOT NULL DEFAULT gen_random_uuid(),
    addendum_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    contract_id uuid NOT NULL,
    project_id uuid NOT NULL,
    description text COLLATE pg_catalog."default",
    additional_value numeric(18, 2) DEFAULT 0,
    addendum_date date,
    company_id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_addendums_pkey PRIMARY KEY (addendum_id),
    CONSTRAINT project_addendums_unique_code_per_company UNIQUE (company_id, addendum_code)
);

CREATE TABLE IF NOT EXISTS public.project_contracts
(
    contract_id uuid NOT NULL DEFAULT gen_random_uuid(),
    contract_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    project_id uuid NOT NULL,
    client_id uuid NOT NULL,
    contract_date date,
    start_date date,
    end_date date,
    contract_value numeric(18, 2) DEFAULT 0,
    payment_term_days integer DEFAULT 0,
    description text COLLATE pg_catalog."default",
    company_id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_contracts_pkey PRIMARY KEY (contract_id),
    CONSTRAINT project_contracts_unique_code_per_company UNIQUE (company_id, contract_code)
);

CREATE TABLE IF NOT EXISTS public.project_details
(
    detail_id uuid NOT NULL DEFAULT gen_random_uuid(),
    project_id uuid NOT NULL,
    item_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    volume numeric(18, 2),
    unit character varying(30) COLLATE pg_catalog."default",
    unit_price numeric(18, 2),
    discount_percent numeric(5, 2) DEFAULT 0,
    discount_amount numeric(18, 2) DEFAULT 0,
    total_price numeric(18, 2),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_details_pkey PRIMARY KEY (detail_id)
);

CREATE TABLE IF NOT EXISTS public.project_invoice_details
(
    invoice_detail_id uuid NOT NULL DEFAULT gen_random_uuid(),
    invoice_id uuid NOT NULL,
    project_detail_id uuid,
    description text COLLATE pg_catalog."default",
    qty numeric(18, 2),
    unit_price numeric(18, 2),
    discount_amount numeric(18, 2) DEFAULT 0,
    amount numeric(18, 2),
    CONSTRAINT project_invoice_details_pkey PRIMARY KEY (invoice_detail_id)
);

CREATE TABLE IF NOT EXISTS public.project_invoices
(
    invoice_id uuid NOT NULL DEFAULT gen_random_uuid(),
    invoice_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    project_id uuid NOT NULL,
    client_id uuid NOT NULL,
    invoice_date date,
    due_date date,
    amount numeric(18, 2) DEFAULT 0,
    tax_amount numeric(18, 2) DEFAULT 0,
    status character varying(30) COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    progress_id uuid,
    CONSTRAINT project_invoices_pkey PRIMARY KEY (invoice_id),
    CONSTRAINT project_invoices_invoice_code_key UNIQUE (invoice_code)
);

CREATE TABLE IF NOT EXISTS public.project_payments
(
    payment_id uuid NOT NULL DEFAULT gen_random_uuid(),
    project_id uuid NOT NULL,
    invoice_id uuid,
    payment_date date,
    amount numeric(18, 2) DEFAULT 0,
    payment_method character varying(30) COLLATE pg_catalog."default",
    bank_account_id uuid,
    reference_no character varying(50) COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'SUCCESS'::character varying,
    notes text COLLATE pg_catalog."default",
    paid_by uuid,
    CONSTRAINT project_payments_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.project_progress
(
    progress_id uuid NOT NULL DEFAULT gen_random_uuid(),
    project_id uuid NOT NULL,
    progress_date date,
    percentage numeric(5, 2) DEFAULT 0,
    description text COLLATE pg_catalog."default",
    reported_by uuid,
    company_id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_progress_pkey PRIMARY KEY (progress_id),
    CONSTRAINT unique_progress_per_day UNIQUE (project_id, progress_date)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    project_id uuid NOT NULL DEFAULT gen_random_uuid(),
    project_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    client_id uuid NOT NULL,
    project_manager_id uuid,
    project_type character varying(50) COLLATE pg_catalog."default",
    status character varying(30) COLLATE pg_catalog."default",
    start_date date,
    end_date date,
    contract_value numeric(18, 2) DEFAULT 0,
    budget_cost numeric(18, 2) DEFAULT 0,
    progress_percent numeric(5, 2) DEFAULT 0,
    location text COLLATE pg_catalog."default",
    is_closed boolean DEFAULT false,
    closed_at timestamp without time zone,
    company_id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT projects_pkey PRIMARY KEY (project_id),
    CONSTRAINT projects_unique_code_per_company UNIQUE (company_id, project_code)
);

CREATE TABLE IF NOT EXISTS public.purchase_items
(
    purchase_item_id uuid NOT NULL DEFAULT gen_random_uuid(),
    purchase_id uuid NOT NULL,
    item_name character varying(200) COLLATE pg_catalog."default",
    qty numeric(18, 2),
    unit character varying(30) COLLATE pg_catalog."default",
    unit_price numeric(18, 2),
    discount_percent numeric(5, 2) DEFAULT 0,
    discount_amount numeric(18, 2) DEFAULT 0,
    total_price numeric(18, 2),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT purchase_items_pkey PRIMARY KEY (purchase_item_id)
);

CREATE TABLE IF NOT EXISTS public.purchase_return_items
(
    return_item_id uuid NOT NULL DEFAULT gen_random_uuid(),
    return_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity numeric(18, 2) NOT NULL,
    unit_price numeric(18, 2) NOT NULL,
    total numeric(18, 2) DEFAULT 0,
    CONSTRAINT purchase_return_items_pkey PRIMARY KEY (return_item_id)
);

CREATE TABLE IF NOT EXISTS public.purchases
(
    purchase_id uuid NOT NULL DEFAULT gen_random_uuid(),
    purchase_code character varying(30) COLLATE pg_catalog."default",
    supplier_id uuid NOT NULL,
    project_id uuid,
    purchase_date date,
    due_date date,
    payment_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    total_amount numeric(18, 2) DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'DRAFT'::character varying,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT purchases_pkey PRIMARY KEY (purchase_id),
    CONSTRAINT purchases_purchase_code_key UNIQUE (purchase_code)
);

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    role_permission_id uuid NOT NULL DEFAULT gen_random_uuid(),
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_permission_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id uuid NOT NULL DEFAULT gen_random_uuid(),
    role_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id),
    CONSTRAINT roles_role_name_key UNIQUE (role_name)
);

CREATE TABLE IF NOT EXISTS public.stock_adjustment_items
(
    adjustment_item_id uuid NOT NULL DEFAULT gen_random_uuid(),
    adjustment_id uuid NOT NULL,
    product_id uuid NOT NULL,
    system_qty numeric(18, 2) NOT NULL,
    actual_qty numeric(18, 2) NOT NULL,
    difference_qty numeric(18, 2) NOT NULL,
    CONSTRAINT stock_adjustment_items_pkey PRIMARY KEY (adjustment_item_id)
);

CREATE TABLE IF NOT EXISTS public.stock_adjustments
(
    adjustment_id uuid NOT NULL DEFAULT gen_random_uuid(),
    adjustment_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    warehouse_id uuid NOT NULL,
    adjustment_date date NOT NULL,
    reason text COLLATE pg_catalog."default",
    total_difference numeric(18, 2) DEFAULT 0,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT stock_adjustments_pkey PRIMARY KEY (adjustment_id),
    CONSTRAINT stock_adjustments_adjustment_code_key UNIQUE (adjustment_code)
);

CREATE TABLE IF NOT EXISTS public.stock_in
(
    stock_in_id uuid NOT NULL DEFAULT gen_random_uuid(),
    grn_id uuid,
    warehouse_id uuid NOT NULL,
    stock_in_date date NOT NULL,
    total_amount numeric(18, 2) DEFAULT 0,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT stock_in_pkey PRIMARY KEY (stock_in_id)
);

CREATE TABLE IF NOT EXISTS public.stock_items
(
    stock_id uuid NOT NULL DEFAULT gen_random_uuid(),
    product_id uuid NOT NULL,
    warehouse_id uuid NOT NULL,
    qty_on_hand numeric(18, 2) DEFAULT 0,
    qty_reserved numeric(18, 2) DEFAULT 0,
    qty_available numeric(18, 2) DEFAULT 0,
    company_id uuid,
    CONSTRAINT stock_items_pkey PRIMARY KEY (stock_id)
);

CREATE TABLE IF NOT EXISTS public.stock_movements
(
    movement_id uuid NOT NULL DEFAULT gen_random_uuid(),
    movement_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    product_id uuid NOT NULL,
    warehouse_id uuid NOT NULL,
    movement_type character varying(30) COLLATE pg_catalog."default",
    reference_type character varying(30) COLLATE pg_catalog."default",
    reference_id uuid,
    quantity numeric(18, 2) NOT NULL,
    movement_date date NOT NULL,
    description text COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT stock_movements_pkey PRIMARY KEY (movement_id),
    CONSTRAINT stock_movements_movement_code_key UNIQUE (movement_code)
);

CREATE TABLE IF NOT EXISTS public.stock_out
(
    stock_out_id uuid NOT NULL DEFAULT gen_random_uuid(),
    project_id uuid,
    warehouse_id uuid NOT NULL,
    stock_out_date date NOT NULL,
    purpose character varying(50) COLLATE pg_catalog."default",
    total_amount numeric(18, 2) DEFAULT 0,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT stock_out_pkey PRIMARY KEY (stock_out_id)
);

CREATE TABLE IF NOT EXISTS public.stock_out_items
(
    stock_out_item_id uuid NOT NULL DEFAULT gen_random_uuid(),
    stock_out_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity numeric(18, 2) NOT NULL,
    unit_cost numeric(18, 2) DEFAULT 0,
    total numeric(18, 2) DEFAULT 0,
    CONSTRAINT stock_out_items_pkey PRIMARY KEY (stock_out_item_id)
);

CREATE TABLE IF NOT EXISTS public.stock_transfer_items
(
    transfer_item_id uuid NOT NULL DEFAULT gen_random_uuid(),
    transfer_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity numeric(18, 2) NOT NULL,
    CONSTRAINT stock_transfer_items_pkey PRIMARY KEY (transfer_item_id)
);

CREATE TABLE IF NOT EXISTS public.stock_transfers
(
    transfer_id uuid NOT NULL DEFAULT gen_random_uuid(),
    transfer_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    from_warehouse_id uuid NOT NULL,
    to_warehouse_id uuid NOT NULL,
    transfer_date date NOT NULL,
    status character varying(30) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT stock_transfers_pkey PRIMARY KEY (transfer_id),
    CONSTRAINT stock_transfers_transfer_code_key UNIQUE (transfer_code)
);

CREATE TABLE IF NOT EXISTS public.supplier_payables
(
    payable_id uuid NOT NULL DEFAULT gen_random_uuid(),
    supplier_id uuid NOT NULL,
    project_id uuid,
    reference_type character varying(30) COLLATE pg_catalog."default",
    purchase_id uuid,
    total_amount numeric(18, 2),
    paid_amount numeric(18, 2) DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'OPEN'::character varying,
    due_date date,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT supplier_payables_pkey PRIMARY KEY (payable_id)
);

CREATE TABLE IF NOT EXISTS public.supplier_payments
(
    payment_id uuid NOT NULL DEFAULT gen_random_uuid(),
    payable_id uuid NOT NULL,
    supplier_id uuid NOT NULL,
    payment_date date NOT NULL,
    amount numeric(18, 2) NOT NULL,
    payment_method character varying(30) COLLATE pg_catalog."default",
    bank_account_id uuid,
    reference_no character varying(50) COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT supplier_payments_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.suppliers
(
    supplier_id uuid NOT NULL DEFAULT gen_random_uuid(),
    supplier_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    supplier_type character varying(50) COLLATE pg_catalog."default",
    npwp character varying(30) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default",
    province character varying(100) COLLATE pg_catalog."default",
    postal_code character varying(10) COLLATE pg_catalog."default",
    country character varying(100) COLLATE pg_catalog."default" DEFAULT 'Indonesia'::character varying,
    phone character varying(30) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    contact_person character varying(100) COLLATE pg_catalog."default",
    contact_phone character varying(30) COLLATE pg_catalog."default",
    payment_term_days integer DEFAULT 0,
    credit_limit numeric(18, 2) DEFAULT 0,
    bank_name character varying(100) COLLATE pg_catalog."default",
    bank_account_number character varying(50) COLLATE pg_catalog."default",
    bank_account_name character varying(150) COLLATE pg_catalog."default",
    pkp character varying COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by uuid,
    updated_at timestamp without time zone,
    updated_by uuid,
    deleted_at timestamp without time zone,
    CONSTRAINT suppliers_pkey PRIMARY KEY (supplier_id),
    CONSTRAINT suppliers_supplier_code_key UNIQUE (supplier_code)
);

CREATE TABLE IF NOT EXISTS public.tax_certificates
(
    certificate_id uuid NOT NULL DEFAULT gen_random_uuid(),
    certificate_number character varying(50) COLLATE pg_catalog."default",
    pph_id uuid,
    supplier_id uuid,
    client_id uuid,
    issue_date date,
    amount numeric(18, 2),
    file_url text COLLATE pg_catalog."default",
    company_id uuid,
    CONSTRAINT tax_certificates_pkey PRIMARY KEY (certificate_id),
    CONSTRAINT tax_certificates_certificate_number_key UNIQUE (certificate_number)
);

CREATE TABLE IF NOT EXISTS public.tax_mappings
(
    mapping_id uuid NOT NULL DEFAULT gen_random_uuid(),
    tax_id uuid NOT NULL,
    reference_type character varying(30) COLLATE pg_catalog."default",
    reference_id uuid,
    coa_input_id uuid,
    coa_output_id uuid,
    is_active boolean DEFAULT true,
    company_id uuid,
    CONSTRAINT tax_mappings_pkey PRIMARY KEY (mapping_id)
);

CREATE TABLE IF NOT EXISTS public.tax_validation_logs
(
    validation_id uuid NOT NULL DEFAULT gen_random_uuid(),
    reference_type character varying(30) COLLATE pg_catalog."default",
    reference_id uuid,
    validation_type character varying(50) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    message text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tax_validation_logs_pkey PRIMARY KEY (validation_id)
);

CREATE TABLE IF NOT EXISTS public.taxes
(
    tax_id uuid NOT NULL DEFAULT gen_random_uuid(),
    tax_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tax_type character varying(30) COLLATE pg_catalog."default",
    rate numeric(5, 2) DEFAULT 0,
    is_included boolean DEFAULT false,
    is_active boolean DEFAULT true,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT taxes_pkey PRIMARY KEY (tax_id),
    CONSTRAINT taxes_tax_code_key UNIQUE (tax_code)
);

CREATE TABLE IF NOT EXISTS public.trial_balance
(
    trial_id uuid NOT NULL DEFAULT gen_random_uuid(),
    coa_id uuid NOT NULL,
    period_month integer,
    period_year integer,
    opening_balance numeric(18, 2) DEFAULT 0,
    debit numeric(18, 2) DEFAULT 0,
    credit numeric(18, 2) DEFAULT 0,
    closing_balance numeric(18, 2) DEFAULT 0,
    company_id uuid,
    CONSTRAINT trial_balance_pkey PRIMARY KEY (trial_id)
);

CREATE TABLE IF NOT EXISTS public.unit_conversions
(
    conversion_id uuid NOT NULL DEFAULT gen_random_uuid(),
    from_unit_id uuid NOT NULL,
    to_unit_id uuid NOT NULL,
    conversion_rate numeric(18, 6) NOT NULL,
    description text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    company_id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT unit_conversions_pkey PRIMARY KEY (conversion_id),
    CONSTRAINT unit_conversions_company_id_from_unit_id_to_unit_id_key UNIQUE (company_id, from_unit_id, to_unit_id)
);

CREATE TABLE IF NOT EXISTS public.units
(
    unit_id uuid NOT NULL DEFAULT gen_random_uuid(),
    unit_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    symbol character varying(20) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    company_id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT units_pkey PRIMARY KEY (unit_id),
    CONSTRAINT units_company_id_unit_code_key UNIQUE (company_id, unit_code)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_role_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_role_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id uuid NOT NULL DEFAULT gen_random_uuid(),
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(150) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    phone character varying(30) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by uuid,
    updated_at timestamp without time zone,
    updated_by uuid,
    role character varying(30) COLLATE pg_catalog."default" DEFAULT 'ADMIN'::character varying,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.vat_in
(
    vat_in_id uuid NOT NULL DEFAULT gen_random_uuid(),
    grn_id uuid,
    purchase_id uuid,
    tax_base numeric(18, 2) DEFAULT 0,
    tax_amount numeric(18, 2) DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vat_in_pkey PRIMARY KEY (vat_in_id)
);

CREATE TABLE IF NOT EXISTS public.vat_out
(
    vat_out_id uuid NOT NULL DEFAULT gen_random_uuid(),
    invoice_id uuid,
    tax_base numeric(18, 2) DEFAULT 0,
    tax_amount numeric(18, 2) DEFAULT 0,
    vat_number character varying(50) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT vat_out_pkey PRIMARY KEY (vat_out_id)
);

CREATE TABLE IF NOT EXISTS public.vat_summary
(
    vat_summary_id uuid NOT NULL DEFAULT gen_random_uuid(),
    period_month integer,
    period_year integer,
    total_vat_out numeric(18, 2) DEFAULT 0,
    total_vat_in numeric(18, 2) DEFAULT 0,
    vat_payable numeric(18, 2) DEFAULT 0,
    company_id uuid,
    CONSTRAINT vat_summary_pkey PRIMARY KEY (vat_summary_id)
);

CREATE TABLE IF NOT EXISTS public.warehouses
(
    warehouse_id uuid NOT NULL DEFAULT gen_random_uuid(),
    warehouse_code character varying(30) COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    is_main boolean DEFAULT false,
    is_active boolean DEFAULT true,
    company_id uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT warehouses_pkey PRIMARY KEY (warehouse_id),
    CONSTRAINT warehouses_warehouse_code_key UNIQUE (warehouse_code)
);

ALTER TABLE IF EXISTS public.bank_accounts
    ADD CONSTRAINT fk_bank_coa FOREIGN KEY (coa_id)
    REFERENCES public.chart_of_accounts (coa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_bank_coa
    ON public.bank_accounts(coa_id);


ALTER TABLE IF EXISTS public.bank_accounts
    ADD CONSTRAINT fk_bank_company FOREIGN KEY (company_id)
    REFERENCES public.company (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_bank_company
    ON public.bank_accounts(company_id);


ALTER TABLE IF EXISTS public.chart_of_accounts
    ADD CONSTRAINT fk_coa_parent FOREIGN KEY (parent_id)
    REFERENCES public.chart_of_accounts (coa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_coa_parent
    ON public.chart_of_accounts(parent_id);


ALTER TABLE IF EXISTS public.coa_mapping_lines
    ADD CONSTRAINT fk_coa FOREIGN KEY (coa_id)
    REFERENCES public.chart_of_accounts (coa_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_mapping_lines
    ADD CONSTRAINT fk_mapping FOREIGN KEY (mapping_id)
    REFERENCES public.coa_mapping (mapping_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grn
    ADD CONSTRAINT fk_grn_purchase FOREIGN KEY (purchase_id)
    REFERENCES public.purchases (purchase_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grn
    ADD CONSTRAINT fk_grn_supplier FOREIGN KEY (supplier_id)
    REFERENCES public.suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grn_items
    ADD CONSTRAINT fk_grn_items FOREIGN KEY (grn_id)
    REFERENCES public.grn (grn_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_brands
    ADD CONSTRAINT fk_brand_company FOREIGN KEY (company_id)
    REFERENCES public.company (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_categories
    ADD CONSTRAINT fk_category_company FOREIGN KEY (company_id)
    REFERENCES public.company (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.project_addendums
    ADD CONSTRAINT fk_addendum_contract FOREIGN KEY (contract_id)
    REFERENCES public.project_contracts (contract_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.project_addendums
    ADD CONSTRAINT fk_addendum_project FOREIGN KEY (project_id)
    REFERENCES public.projects (project_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.project_contracts
    ADD CONSTRAINT fk_contract_client FOREIGN KEY (client_id)
    REFERENCES public.clients (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.project_contracts
    ADD CONSTRAINT fk_contract_project FOREIGN KEY (project_id)
    REFERENCES public.projects (project_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.project_details
    ADD CONSTRAINT fk_detail_project FOREIGN KEY (project_id)
    REFERENCES public.projects (project_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.project_invoice_details
    ADD CONSTRAINT fk_inv_detail_invoice FOREIGN KEY (invoice_id)
    REFERENCES public.project_invoices (invoice_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.project_progress
    ADD CONSTRAINT fk_progress_project FOREIGN KEY (project_id)
    REFERENCES public.projects (project_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.project_progress
    ADD CONSTRAINT fk_progress_user FOREIGN KEY (reported_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT fk_projects_client FOREIGN KEY (client_id)
    REFERENCES public.clients (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.unit_conversions
    ADD CONSTRAINT fk_uc_company FOREIGN KEY (company_id)
    REFERENCES public.company (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.unit_conversions
    ADD CONSTRAINT fk_uc_from_unit FOREIGN KEY (from_unit_id)
    REFERENCES public.units (unit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.unit_conversions
    ADD CONSTRAINT fk_uc_to_unit FOREIGN KEY (to_unit_id)
    REFERENCES public.units (unit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.units
    ADD CONSTRAINT fk_unit_company FOREIGN KEY (company_id)
    REFERENCES public.company (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;